### ISSUE TITLE
Loader Component Incorrectly Positioned on Mobile

### ISSUE THREAD

**Issue by Splode** [Splode/open-trivia-app#1]
The "worm" loader is incorrectly positioned when displayed on mobile (iOS) browsers, including both Chrome and Safari. This loader should be centered both horizontally and vertically and uses flexbox to achieve this positioning. Positioning works as intended on desktop.

This issue cannot be simulated using Chrome dev tools; it appears only on an actual device.

**Comment by Splode** [comment]
# Resolved
Required explicitly setting the height of the parent container:

**Original**
````css
.wrapper {
  height: 100%;
}
````
**Fix**
````css
.wrapper {
  height: 80vh;
}
````
